/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "system_stm32f4xx.h"

#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_utils.h"
#include "stm32f4xx_ll_bus.h"

void SysTick_Handler(void);
extern uint32_t SystemCoreClock;
// #include "stm32f4xx_hal_adc.h"

int main(void)
{
  SystemInit();
  SystemCoreClockUpdate();
  /* Set systick to 1ms */
  SysTick_Config(SystemCoreClock / 1000);
  LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOC);
  LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

  /* Configure IO in output push-pull mode to drive external LED1 */
  LL_GPIO_SetPinMode(GPIOC, LL_GPIO_PIN_13, LL_GPIO_MODE_OUTPUT);
  LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_0, LL_GPIO_MODE_INPUT);
  LL_GPIO_SetPinPull(GPIOA, LL_GPIO_PIN_0, LL_GPIO_PULL_UP);
  /* Loop forever */
  for (;;)
  {
    LL_GPIO_TogglePin(GPIOC, LL_GPIO_PIN_13);
    if(LL_GPIO_ReadInputPort(GPIOA) & 1)
    {
      LL_mDelay(250);
    }
    else
    {
      LL_mDelay(50);
    }
  }
}

/**
  * @brief  This function handles SysTick Handler.
  * @param  None
  * @retval None
  */
void SysTick_Handler(void)
{
}
